### ISSUE TITLE
想问一下这个插件是否支持找出中文的词语的潜在链接

### ISSUE THREAD

**Issue by Tcould** [Medill-East/obsidian-content-linker#1]
开发者你好!想问一下这个插件是否支持找出中文的词语的潜在链接，找了设置并未发现相关的设置，若能受到您的回复，万分感谢！

**Comment by Medill-East** [comment]
不好意思，之前没注意，正则表达没增加对中文字词的支持，现在应该可以了，得了1.4版本再试试呢~

**Comment by Tcould** [comment]
感谢您的修改！现在搜索潜在词已经支持中文了，但是无法对此建立双链，测试后发现只有英文单词可以建立双链。如下图所示。望您有空的时候能做出修改，最后特别感谢您的开发。
![screenshots](https://github.com/Medill-East/obsidian-content-linker/assets/127692738/c02bba60-0afb-4822-866e-0bbaa6af0533)

**Comment by Medill-East** [comment]
更新了，拉 1.5.1 版本试试呢

**Comment by Tcould** [comment]
好了！可以啦！感谢作者大大
